spring:
  application:
    name: wanblog

server:
  port: 80

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wanblog:
  jwt:
    secret: wanblog
    expire: 604800
    header: Authorization